#!/bin/bash

if [[ $1 == '-h' || $1 == '--help' ]]
then
    echo "GoS game businesses restarter 1.2.1"
    echo "Should support Herb Gardens, Kitchens, Breweries, Mines, Farms."
    echo "Usage:" `basename $0` "NAME HOUSE PASSWORD [BIZNUM PRODUCT CITY BIZVAL CELL_COUNT COOKIES_DIR]"
    echo ""
    echo "BIZNUM is business ID. 8 is Mine, 5 is Brewery, 7 is Farm. You can find out ID for another business with Firebug or analogue, first parameter for subAction(). By default will work with mines."
    echo "PRODUCT is type of good. Default is 12 (most advanced for mines and other except Farms, where most advanced is 18)."
    echo "CITY in which to work. Default to current. If provided with value that doesn't match current city, will Skim to it, work, and Skim back."
    echo "BIZVAL is unknown to me. Default 0."
    echo "CELL_COUNT is number of purchased cells for this business in this city. Default to 9 (all possible). Helps saving time and traffic, nothing more."
    echo "COOKIES_DIR is path to diurectoryyou want script to store cookies while it's working. Default to curent directory."
    echo ""
    echo "Parallel work with different characters should be supported, but wasn't tested."
    echo ""
    echo "Report bugs here: https://github.com/egilewski/gos-business-restarter"
    exit
fi

BASEURL='http://gos.talij.com/'
LOGINURL="$BASEURL"'verify.php'
BUSINESSURL="$BASEURL"'mybusinesses.php'
WORLDURL="$BASEURL"'world.php'
TRAVELURL="$BASEURL"'map/traveling.php'
FEEDURL="$BASEURL"'business.php?shop=4&feed=1'

NAME=$1
HOUSE=$2
PASSWORD=$3

BIZACT_SELL=5
BIZACT_START=4

BIZNUM=${4:-8}
PRODUCT=${5:-12}
CITY=$6
BIZVAL=${7:-0}
CELL_COUNT=${8:-9}
COOKIES_FILE="${9:-.}/gos-cookies.txt-$$"

WGET_OPTIONS="-q --load-cookies $COOKIES_FILE"


# Skimming.
skim () {
    destination_city=$1
    destination_city_encoded="$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$destination_city")"

    echo -n "Moving to $destination_city... "
    # Go to city.
    wget -O /dev/null $WGET_OPTIONS \
            --post-data="goto=$destination_city_encoded&dir=1" \
            "$TRAVELURL"
    # Feed horse.
    wget -O /dev/null $WGET_OPTIONS \
            "$FEEDURL"
    echo "done"
}


# Cleanup before exiting.
cleanup () {
    echo -n 'Cleaning up... '
    rm -f "$COOKIES_FILE"
    echo 'done'
}


# Cleanup on user interrupt.
# Important: remove cookies with password.
trap "cleanup" EXIT


# Login.
echo -n "Logging in as $NAME $HOUSE... "
wget -q -O /dev/null \
        --save-cookies "$COOKIES_FILE" \
        --post-data="lastname=$HOUSE&password=$PASSWORD&userid=$NAME&mode=0&submit=Enter+World" \
        "$LOGINURL"
echo "done"


# Check if we are in desired city and move to it otherwise.
if [[ "$CITY" ]]
then
    echo -n "Checking current city... "
    current_city=`wget -O - $WGET_OPTIONS "$WORLDURL" | grep -oP "(?<=<div id='message' class='littletext_b'>)[^<]*"` 
    echo "$current_city"
    if [[ "$current_city" != "$CITY" ]]
    then
        skim "$CITY"
        return_to_city="$current_city"
    fi
fi


# For every cell in business (will do nothing for cells not bought).
for cell_number in `seq 0 $((CELL_COUNT-1))`
do
    # Match game interface cell number.
    interface_cell_number=$((cell_number+1))

    # Sell good and start new production.
    echo -n "Selling cell #$interface_cell_number... "
    wget -O /dev/null $WGET_OPTIONS \
            --post-data="biznum=$BIZNUM&bizact=$BIZACT_SELL&bizval=$BIZVAL&bizsub=$cell_number" \
            "$BUSINESSURL"
    echo "done"

    echo -n "Starting cell #$interface_cell_number... "
    wget -O /dev/null $WGET_OPTIONS \
            --post-data="biznum=$BIZNUM&bizact=$BIZACT_START&bizval=$BIZVAL&bizsub=$cell_number&product=$PRODUCT" \
            "$BUSINESSURL"
    echo "done"
done


# Return to original city.
if [[ "$return_to_city" ]]
then
    skim "$return_to_city"
fi
